namespace Lokad.Utf8Regex.Internal.Diagnostics;

internal enum Utf8ExecutionRoute : byte
{
    None = 0,
    CompiledFusedAsciiLiteralFamilyCount,
    CompiledFusedUtf8LiteralCount,
    CompiledFusedUtf8LiteralFamilyCount,
    RequiredPrefilterReject,
    NativeStructuralFamilyEmitSharedPrefixSuffix,
    NativeAsciiBoundedSuffixLiteral,
    NativeStructuralFamily,
    NativeAsciiAnchoredValidator,
    NativeAsciiSimplePatternFixedAlternation,
    NativeAsciiSimplePatternFixedLength,
    NativeAsciiSimplePattern,
    FallbackByteSafeLinear,
    FallbackDirectRegex,
    FallbackSearchGuided,
    FallbackSearchGuidedDemoted,
    FallbackCompiled,
    FallbackDirectAnchoredQuotedLineSegment,
    FallbackDirectLinePrefix,
    FallbackDirectUnicodeLetterBounded,
    FallbackDirectUnicodeLetter,
    FallbackDirectUnicodeCategory,
    FallbackDirectAsciiEmittedTokenFamily,
    FallbackDirectAsciiWordBounded,
    FallbackDirectAsciiDottedDecimalQuad,
    FallbackDirectAsciiUntilByteStar,
    FallbackDirectAsciiDelimitedToken,
    FallbackDirectUtf8WordDelimitedToken,
    FallbackDirectAsciiLiteralStructuredToken,
    FallbackDirectAsciiIdentifierToken,
    FallbackDirectAsciiIpv4Token,
    FallbackDirectAsciiUriToken,
    FallbackDirectAsciiBoundedDateToken,
    NativeStructuralLinearAutomaton,
    LiteralFamilyHybridEarliestAutomaton,
    LiteralFamilyPreparedNonOverlapping,
    LiteralFamilyPreparedWithRequirementsLengthOnly,
    LiteralFamilyPreparedWithRequirementsMatch,
    NativeAsciiCharClassRun,
    NativeOrderedLiteralWindow,
    NativeStructuralFamilyEmitUpperWordIdentifier,
    NativeOrderedLiteralWindowEmitBoundedGapLiteral,
    NativeOrderedLiteralWindowEmitSeparatorLiteral,
    NativeStructuralFamilyEmit,
    NativeStructuralFamilySuffix,
    NativeStructuralFamilyLinear,
    NativeStructuralLinearEmit,
    NativeAsciiSimplePatternRepeatedDigitGroup,
    NativeAsciiSimplePatternSymmetricLiteralWindowCompiled,
    NativeAsciiSimplePatternSymmetricLiteralWindow,
}

internal static class Utf8ExecutionRouteText
{
    public static string Format(this Utf8ExecutionRoute route) => route switch
    {
        Utf8ExecutionRoute.None => "<none>",
        Utf8ExecutionRoute.CompiledFusedAsciiLiteralFamilyCount => "compiled_fused_ascii_literal_family_count",
        Utf8ExecutionRoute.CompiledFusedUtf8LiteralCount => "compiled_fused_utf8_literal_count",
        Utf8ExecutionRoute.CompiledFusedUtf8LiteralFamilyCount => "compiled_fused_utf8_literal_family_count",
        Utf8ExecutionRoute.RequiredPrefilterReject => "required_prefilter_reject",
        Utf8ExecutionRoute.NativeStructuralFamilyEmitSharedPrefixSuffix => "native_structural_family_emit_shared_prefix_suffix",
        Utf8ExecutionRoute.NativeAsciiBoundedSuffixLiteral => "native_ascii_bounded_suffix_literal",
        Utf8ExecutionRoute.NativeStructuralFamily => "native_structural_family",
        Utf8ExecutionRoute.NativeAsciiAnchoredValidator => "native_ascii_anchored_validator",
        Utf8ExecutionRoute.NativeAsciiSimplePatternFixedAlternation => "native_ascii_simple_pattern_fixed_alternation",
        Utf8ExecutionRoute.NativeAsciiSimplePatternFixedLength => "native_ascii_simple_pattern_fixed_length",
        Utf8ExecutionRoute.NativeAsciiSimplePattern => "native_ascii_simple_pattern",
        Utf8ExecutionRoute.FallbackByteSafeLinear => "fallback_byte_safe_linear",
        Utf8ExecutionRoute.FallbackDirectRegex => "fallback_direct_regex",
        Utf8ExecutionRoute.FallbackSearchGuided => "fallback_search_guided",
        Utf8ExecutionRoute.FallbackSearchGuidedDemoted => "fallback_search_guided_demoted",
        Utf8ExecutionRoute.FallbackCompiled => "fallback_compiled",
        Utf8ExecutionRoute.FallbackDirectAnchoredQuotedLineSegment => "fallback_direct_anchored_quoted_line_segment",
        Utf8ExecutionRoute.FallbackDirectLinePrefix => "fallback_direct_line_prefix",
        Utf8ExecutionRoute.FallbackDirectUnicodeLetterBounded => "fallback_direct_unicode_letter_bounded",
        Utf8ExecutionRoute.FallbackDirectUnicodeLetter => "fallback_direct_unicode_letter",
        Utf8ExecutionRoute.FallbackDirectUnicodeCategory => "fallback_direct_unicode_category",
        Utf8ExecutionRoute.FallbackDirectAsciiEmittedTokenFamily => "fallback_direct_ascii_emitted_token_family",
        Utf8ExecutionRoute.FallbackDirectAsciiWordBounded => "fallback_direct_ascii_word_bounded",
        Utf8ExecutionRoute.FallbackDirectAsciiDottedDecimalQuad => "fallback_direct_ascii_dotted_decimal_quad",
        Utf8ExecutionRoute.FallbackDirectAsciiUntilByteStar => "fallback_direct_ascii_until_byte_star",
        Utf8ExecutionRoute.FallbackDirectAsciiDelimitedToken => "fallback_direct_ascii_delimited_token",
        Utf8ExecutionRoute.FallbackDirectUtf8WordDelimitedToken => "fallback_direct_utf8_word_delimited_token",
        Utf8ExecutionRoute.FallbackDirectAsciiLiteralStructuredToken => "fallback_direct_ascii_literal_structured_token",
        Utf8ExecutionRoute.FallbackDirectAsciiIdentifierToken => "fallback_direct_ascii_identifier_token",
        Utf8ExecutionRoute.FallbackDirectAsciiIpv4Token => "fallback_direct_ascii_ipv4_token",
        Utf8ExecutionRoute.FallbackDirectAsciiUriToken => "fallback_direct_ascii_uri_token",
        Utf8ExecutionRoute.FallbackDirectAsciiBoundedDateToken => "fallback_direct_ascii_bounded_date_token",
        Utf8ExecutionRoute.NativeStructuralLinearAutomaton => "native_structural_linear_automaton",
        Utf8ExecutionRoute.LiteralFamilyHybridEarliestAutomaton => "literal_family_hybrid_earliest_automaton",
        Utf8ExecutionRoute.LiteralFamilyPreparedNonOverlapping => "literal_family_prepared_non_overlapping",
        Utf8ExecutionRoute.LiteralFamilyPreparedWithRequirementsLengthOnly => "literal_family_prepared_with_requirements_length_only",
        Utf8ExecutionRoute.LiteralFamilyPreparedWithRequirementsMatch => "literal_family_prepared_with_requirements_match",
        Utf8ExecutionRoute.NativeAsciiCharClassRun => "native_ascii_char_class_run",
        Utf8ExecutionRoute.NativeOrderedLiteralWindow => "native_ordered_literal_window",
        Utf8ExecutionRoute.NativeStructuralFamilyEmitUpperWordIdentifier => "native_structural_family_emit_upper_word_identifier",
        Utf8ExecutionRoute.NativeOrderedLiteralWindowEmitBoundedGapLiteral => "native_ordered_literal_window_emit_bounded_gap_literal",
        Utf8ExecutionRoute.NativeOrderedLiteralWindowEmitSeparatorLiteral => "native_ordered_literal_window_emit_separator_literal",
        Utf8ExecutionRoute.NativeStructuralFamilyEmit => "native_structural_family_emit",
        Utf8ExecutionRoute.NativeStructuralFamilySuffix => "native_structural_family_suffix",
        Utf8ExecutionRoute.NativeStructuralFamilyLinear => "native_structural_family_linear",
        Utf8ExecutionRoute.NativeStructuralLinearEmit => "native_structural_linear_emit",
        Utf8ExecutionRoute.NativeAsciiSimplePatternRepeatedDigitGroup => "native_ascii_simple_pattern_repeated_digit_group",
        Utf8ExecutionRoute.NativeAsciiSimplePatternSymmetricLiteralWindowCompiled => "native_ascii_simple_pattern_symmetric_literal_window_compiled",
        Utf8ExecutionRoute.NativeAsciiSimplePatternSymmetricLiteralWindow => "native_ascii_simple_pattern_symmetric_literal_window",
        _ => throw new InvalidOperationException("Unknown UTF-8 execution route."),
    };
}
